# Generated by Django 2.2.6 on 2019-10-31 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('n', 'N'), ('r', 'R'), ('sr', 'SR'), ('ssr', 'SSR'), ('sp', 'SP')], default='ssr', max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=10)),
                ('formula', models.ManyToManyField(to='onmyoji_models.Formula')),
            ],
        ),
        migrations.CreateModel(
            name='Lover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lover_name', models.CharField(max_length=10, unique=True)),
                ('formula', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onmyoji_models.Formula')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='rare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onmyoji_models.Rare'),
        ),
    ]
