# Generated by Django 2.2.6 on 2019-11-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onmyoji_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soul',
            name='set',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
